### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by bcipolli** [joffotron/rb-lightroom-plugin#1]
If you can add some documentation about how to use this, I'd be happy to try it out and/or update it as needed! Just need a starting point...

**Comment by bcipolli** [comment]
Found some info here: http://artplustech.com/a-first-hack-day-at-redbubble/#3 How to install this in Lightroom would be great!

**Comment by joffotron** [comment]
Hi!

TBH I'm kind of surprised anyone found this! To package and install it in Lightroom, I think (from memory, which is a bit fuzzy), you simply zip it up and install it as a plugin in Lightroom.

**However** this was a hack-day project, built upon a temporary private API we put into the Redbubble codebase, so there is no way that it can currently talk to the site at the moment.

Sorry!

**Comment by bcipolli** [comment]
Sure thing. I kinda figured, once I got into the code :smile: Too bad...
